### ISSUE TITLE
fd cannot be null in adnroid 11

### ISSUE THREAD

**Issue by abbasalim** [pramodkr123/ConvertWebViewToPdfDemo#10]
hello,
in android 11 give this error:

` FATAL EXCEPTION: main
    Process: ir.esfandune.wave, PID: 15997
    java.lang.IllegalArgumentException: fd cannot be null
        at ft.onWrite(chromium-TrichromeWebViewGoogle.apk-stable-410410686:28)
        at android.print.PdfPrint$1.onLayoutFinished(PdfPrint.java:24)
        at ft.onLayout(chromium-TrichromeWebViewGoogle.apk-stable-410410686:4)
        at android.print.PdfPrint.print(PdfPrint.java:20)
        at com.webviewtopdf.PdfView.createWebPrintJob(PdfView.java:53)`
although i added `android:requestLegacyExternalStorage="true"` in manifest.

**Comment by pramodkr123** [comment]
Add this permission in your manifest for android 11.
uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE"

before create pdf check this permission

 

if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {

if(Environment.isExternalStorageManager()) {

// print pdf code here
} else {
//request permission
try {
val intent = Intent(Settings.ACTION_MANAGE_APP_ALL_FILES_ACCESS_PERMISSION)
intent.addCategory("android.intent.category.DEFAULT")
intent.data = Uri.parse(String.format("package:%s", applicationContext.packageName))
startActivityForResult(intent, 1)
} catch (e: Exception) {
val intent = Intent()
intent.action = Settings.ACTION_MANAGE_ALL_FILES_ACCESS_PERMISSION
startActivityForResult(intent, 1)
}
}
}

override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
super.onActivityResult(requestCode, resultCode, data)
if (requestCode==1 && Environment.isExternalStorageManager()){
// print pdf code here
}
}
}

**Comment by dennisrufigill** [comment]
@pramodkr123 Thanks for the amazing library.
Well, after giving permission and using the above code,  I am still getting the same error on Android 11 and 12.

**Comment by pramodkr123** [comment]
Try to use this path to export the pdf.

File exportDir;
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R){
     exportDir = new File(getExternalFilesDir("PDFTest"), "Test.pdf");
} else {
     exportDir = new File(Environment.getExternalStorageDirectory(), "PDFTest/".concat("Test.pdf"));
}

Let me know it's not fix your crash.

**Comment by dennisrufigill** [comment]
It's not working at all. Still facing issues.

**Comment by dennisrufigill** [comment]
I would suggest, if you can update the library as android 11 and 12 has great number of users.
Thanks.

**Comment by qiBerry** [comment]
@dennisrufigill , hello! Have you found a problem why the library not works on android 11?

**Comment by pramodkr123** [comment]
library upgraded please check.
