### ISSUE TITLE
FileProvider not found

### ISSUE THREAD

**Issue by KsgFellow** [pramodkr123/ConvertWebViewToPdfDemo#4]
I get the following Error, even after including provider Tag and everything else as instructed.
Error: `Unable to get provider android.support.v4.content.FileProvider: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.content.FileProvider" on path`

Any insights or advice on this?
I'd be grateful for any help.

**Comment by pramodkr123** [comment]
<provider
        android:name="android.support.v4.content.FileProvider"
        android:authorities="com.package.name.fileprovider" // Here use your package name
        android:exported="false"
        android:grantUriPermissions="true">
        <meta-data
            android:name="android.support.FILE_PROVIDER_PATHS"
            android:resource="@xml/provider_paths" />
    </provider>

suppose your package name is : "com.test"
your authority should be : 
android:authorities="com.test.fileprovider"

Hope it will help 

If you are getting same issue please send me the code of <Provider> tag in Manifest.

Let me know If you are getting issue

**Comment by KsgFellow** [comment]
Thanks for the quick response, I was able to solve it.
